name: CT Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - juice-shop
  
jobs:
  analyze:
    name: CodeQL analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'typescript', 'javascript' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: juice-shop

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        debug: true
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
        
  synopsys-detect:
    name: Software composition analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          ref: feature/TSADS-3347
      - name: Blackduck detection
        shell: bash
        run: |
          set -e -x
          wget https://detect.synopsys.com/detect7.sh
          chmod +x detect7.sh
          ./detect7.sh --blackduck.url="https://ingka.app.blackduck.com" --blackduck.api.token=${{secrets.BLACKDUCK_TOKEN}} --detect.project.name="tez/juice-shop" --detect.project.version.name="V.1" --detect.source.path="../" --detect.detector.search.depth=8 --detect.npm.include.dev.dependencies=true --detect.project.version.distribution="SAAS"
